version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:

  - cmd: dotnet --version
  
  - cmd: dotnet restore ./EdgyBot/EdgyBot/EdgyBot.csproj --verbosity m --configfile ./EdgyBot/.nuget/nuget.config
  - cmd: dotnet restore ./EdgyBot/Discord.Addons.Interactive/Discord.Addons.Interactive.csproj --verbosity m --configfile ./EdgyBot/.nuget/nuget.config
  - cmd: dotnet restore ./EdgyBot/EdgyBot.Database/EdgyBot.Database.csproj --verbosity m
build_script:

  - cmd: dotnet publish ./EdgyBot/EdgyBot/EdgyBot.csproj
  - cmd: dotnet publish ./EdgyBot/Discord.Addons.Interactive/Discord.Addons.Interactive.csproj
  - cmd: dotnet publish ./EdgyBot/EdgyBot.Database/EdgyBot.Database.csproj
after_build:

artifacts:
 - path: '\EdgyBot\EdgyBot\bin\Release\netcoreapp2.0\publish'
   name: EdgyBot
   type: WebDeployPackage
clone_depth: 1
test_script:
on_finish :
  # any cleanup in here
deploy: off
